version: '3'
services:
  fastapi:
    build:
      context: ./market_backend
    ports:
      - "8000:8000"

  nextjs:
    build:
      context: ./market_frontend
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
